name: Ping Render service
on:
  schedule:
    - cron: '*/5 * * * *'   # cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service
        run: curl -fsS https://<tu-servicio>.onrender.com/healthz || exit 1
